name: Build
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04 # required for dmidecode

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-dev python3-distutils python3-libxml2 python3-dmidecode python3-pip python3-lxml
          sudo apt-get install bzip2 sysstat libxml2-dev libnl-route-3-dev build-essential libnuma-dev
          sudo pip3 install ethtool
          wget -P loadsource https://www.kernel.org/pub/linux/kernel/v5.x/linux-5.7.tar.xz
      - name: Build
        run: sudo make
          